export const MyAction = {
    ADD_USER: 'ADD_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILED: 'ADD_USER_FAILED',

    EDIT_USER: 'EDIT_USER',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    REMOVE_USER: 'REMOVE_USER',
    REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
    REMOVE_USER_FAILED: 'REMOVE_USER_FAILED',
};
